
/*******************************************************************************
* This file was generated by UI Builder.
* This file will be auto-generated each and everytime you save your project.
* Do not hand edit this file.
********************************************************************************/
		#include "g_inc_uib.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include "uib_app_manager.h"

/* event handler declarations */
void view1_exitButton_onclicked(uib_view1_view_context*, Evas_Object*, void*);

uib_view_context* uib_view_view1_create(Evas_Object* parent, void* create_callback_param) {
	uib_view1_view_context* vc = calloc(1, sizeof(uib_view1_view_context));
	vc->parent = parent;
	vc->view_name = "view1";
	vc->indicator_state = ELM_WIN_INDICATOR_SHOW;
	vc->is_user_view = false;
	uib_app_manager_get_instance()->add_view_context((uib_view_context*)vc);
	if (!vc->grid1) {
		vc->grid1= elm_grid_add(parent);
		vc->root_container = vc->grid1;
	}
	uib_views_get_instance()->set_targeted_view((uib_view_context*)vc);

	//bind event handler
	evas_object_smart_callback_add(vc->exitButton, "clicked", (Evas_Smart_Cb)view1_exitButton_onclicked, vc);


	evas_object_data_set(vc->root_container, KEY_VIEW_CONTEXT, vc);
	uib_views_create_callback(vc, evas_object_evas_get(vc->root_container), vc->root_container, create_callback_param);
	evas_object_event_callback_add(vc->root_container, EVAS_CALLBACK_DEL, (Evas_Object_Event_Cb)uib_views_destroy_callback, vc);

	return (uib_view_context*)vc;
}
void uib_view1_config_CIRCLE_360x360_portrait() {
	uib_app_manager_st* uib_app_manager = uib_app_manager_get_instance();
	uib_view1_view_context* vc = (uib_view1_view_context*)uib_app_manager->find_view_context("view1");
	if(!vc) {
		return;
	}
	if(vc->grid1) {
		elm_grid_clear(vc->grid1, EINA_FALSE);
		evas_object_size_hint_align_set(vc->grid1, -1.0, -1.0);		evas_object_size_hint_weight_set(vc->grid1, 1.0, 1.0);		elm_grid_size_set(vc->grid1, 1000, 1000);
		if (!vc->label1) {
			vc->label1 = elm_label_add(vc->grid1);
		}
		if(vc->label1) {
			evas_object_size_hint_align_set(vc->label1, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->label1, 1.0, 1.0);			elm_object_text_set(vc->label1,_UIB_LOCALE("Pace"));
			elm_label_line_wrap_set(vc->label1, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->label1,0);
			elm_label_ellipsis_set(vc->label1, EINA_FALSE);
			evas_object_show(vc->label1);
		}
		if (!vc->label2) {
			vc->label2 = elm_label_add(vc->grid1);
		}
		if(vc->label2) {
			evas_object_size_hint_align_set(vc->label2, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->label2, 1.0, 1.0);			elm_object_text_set(vc->label2,_UIB_LOCALE(".1km"));
			elm_label_line_wrap_set(vc->label2, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->label2,0);
			elm_label_ellipsis_set(vc->label2, EINA_FALSE);
			evas_object_show(vc->label2);
		}
		if (!vc->label3) {
			vc->label3 = elm_label_add(vc->grid1);
		}
		if(vc->label3) {
			evas_object_size_hint_align_set(vc->label3, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->label3, 1.0, 1.0);			elm_object_text_set(vc->label3,_UIB_LOCALE("1km"));
			elm_label_line_wrap_set(vc->label3, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->label3,0);
			elm_label_ellipsis_set(vc->label3, EINA_FALSE);
			evas_object_show(vc->label3);
		}
		if (!vc->label4) {
			vc->label4 = elm_label_add(vc->grid1);
		}
		if(vc->label4) {
			evas_object_size_hint_align_set(vc->label4, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->label4, 1.0, 1.0);			elm_object_text_set(vc->label4,_UIB_LOCALE("*km"));
			elm_label_line_wrap_set(vc->label4, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->label4,0);
			elm_label_ellipsis_set(vc->label4, EINA_FALSE);
			evas_object_show(vc->label4);
		}
		if (!vc->label6) {
			vc->label6 = elm_label_add(vc->grid1);
		}
		if(vc->label6) {
			evas_object_size_hint_align_set(vc->label6, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->label6, 1.0, 1.0);			elm_object_text_set(vc->label6,_UIB_LOCALE("1m"));
			elm_label_line_wrap_set(vc->label6, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->label6,0);
			elm_label_ellipsis_set(vc->label6, EINA_FALSE);
			evas_object_show(vc->label6);
		}
		if (!vc->label7) {
			vc->label7 = elm_label_add(vc->grid1);
		}
		if(vc->label7) {
			evas_object_size_hint_align_set(vc->label7, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->label7, 1.0, 1.0);			elm_object_text_set(vc->label7,_UIB_LOCALE("10m"));
			elm_label_line_wrap_set(vc->label7, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->label7,0);
			elm_label_ellipsis_set(vc->label7, EINA_FALSE);
			evas_object_show(vc->label7);
		}
		if (!vc->label8) {
			vc->label8 = elm_label_add(vc->grid1);
		}
		if(vc->label8) {
			evas_object_size_hint_align_set(vc->label8, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->label8, 1.0, 1.0);			elm_object_text_set(vc->label8,_UIB_LOCALE("Dist"));
			elm_label_line_wrap_set(vc->label8, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->label8,0);
			elm_label_ellipsis_set(vc->label8, EINA_FALSE);
			evas_object_show(vc->label8);
		}
		if (!vc->label9) {
			vc->label9 = elm_label_add(vc->grid1);
		}
		if(vc->label9) {
			evas_object_size_hint_align_set(vc->label9, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->label9, 1.0, 1.0);			elm_object_text_set(vc->label9,_UIB_LOCALE("*m"));
			elm_label_line_wrap_set(vc->label9, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->label9,0);
			elm_label_ellipsis_set(vc->label9, EINA_FALSE);
			evas_object_show(vc->label9);
		}
		if (!vc->dkml) {
			vc->dkml = elm_label_add(vc->grid1);
		}
		if(vc->dkml) {
			evas_object_size_hint_align_set(vc->dkml, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->dkml, 1.0, 1.0);			elm_label_line_wrap_set(vc->dkml, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->dkml,0);
			elm_label_ellipsis_set(vc->dkml, EINA_FALSE);
			evas_object_show(vc->dkml);
		}
		if (!vc->kml) {
			vc->kml = elm_label_add(vc->grid1);
		}
		if(vc->kml) {
			evas_object_size_hint_align_set(vc->kml, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->kml, 1.0, 1.0);			elm_label_line_wrap_set(vc->kml, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->kml,0);
			elm_label_ellipsis_set(vc->kml, EINA_FALSE);
			evas_object_show(vc->kml);
		}
		if (!vc->akml) {
			vc->akml = elm_label_add(vc->grid1);
		}
		if(vc->akml) {
			evas_object_size_hint_align_set(vc->akml, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->akml, 1.0, 1.0);			elm_label_line_wrap_set(vc->akml, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->akml,0);
			elm_label_ellipsis_set(vc->akml, EINA_FALSE);
			evas_object_show(vc->akml);
		}
		if (!vc->aml) {
			vc->aml = elm_label_add(vc->grid1);
		}
		if(vc->aml) {
			evas_object_size_hint_align_set(vc->aml, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->aml, 1.0, 1.0);			elm_label_line_wrap_set(vc->aml, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->aml,0);
			elm_label_ellipsis_set(vc->aml, EINA_FALSE);
			evas_object_show(vc->aml);
		}
		if (!vc->dml) {
			vc->dml = elm_label_add(vc->grid1);
		}
		if(vc->dml) {
			evas_object_size_hint_align_set(vc->dml, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->dml, 1.0, 1.0);			elm_label_line_wrap_set(vc->dml, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->dml,0);
			elm_label_ellipsis_set(vc->dml, EINA_FALSE);
			evas_object_show(vc->dml);
		}
		if (!vc->ml) {
			vc->ml = elm_label_add(vc->grid1);
		}
		if(vc->ml) {
			evas_object_size_hint_align_set(vc->ml, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->ml, 1.0, 1.0);			elm_label_line_wrap_set(vc->ml, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->ml,0);
			elm_label_ellipsis_set(vc->ml, EINA_FALSE);
			evas_object_show(vc->ml);
		}
		if (!vc->hrml) {
			vc->hrml = elm_label_add(vc->grid1);
		}
		if(vc->hrml) {
			evas_object_size_hint_align_set(vc->hrml, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->hrml, 1.0, 1.0);			elm_label_line_wrap_set(vc->hrml, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->hrml,0);
			elm_label_ellipsis_set(vc->hrml, EINA_FALSE);
			evas_object_show(vc->hrml);
		}
		if (!vc->label10) {
			vc->label10 = elm_label_add(vc->grid1);
		}
		if(vc->label10) {
			evas_object_size_hint_align_set(vc->label10, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->label10, 1.0, 1.0);			elm_object_text_set(vc->label10,_UIB_LOCALE("HR"));
			elm_label_line_wrap_set(vc->label10, (Elm_Wrap_Type)ELM_WRAP_NONE);
			elm_label_wrap_width_set(vc->label10,0);
			elm_label_ellipsis_set(vc->label10, EINA_FALSE);
			evas_object_show(vc->label10);
		}
		if (!vc->exitButton) {
			vc->exitButton = elm_button_add(vc->grid1);
		}
		if (vc->exitButton) {
			evas_object_size_hint_align_set(vc->exitButton, -1.0, -1.0);			evas_object_size_hint_weight_set(vc->exitButton, 1.0, 1.0);			elm_object_text_set(vc->exitButton,_UIB_LOCALE("X"));
			elm_object_style_set(vc->exitButton,"default");
			evas_object_show(vc->exitButton);
		}
		elm_grid_pack(vc->grid1, vc->label1, 367, 34, 236, 103);		elm_grid_pack(vc->grid1, vc->label2, 169, 133, 272, 112);		elm_grid_pack(vc->grid1, vc->label3, 167, 264, 272, 114);		elm_grid_pack(vc->grid1, vc->label4, 177, 398, 262, 114);		elm_grid_pack(vc->grid1, vc->label6, 167, 750, 272, 114);		elm_grid_pack(vc->grid1, vc->label7, 167, 639, 272, 114);		elm_grid_pack(vc->grid1, vc->label8, 367, 866, 236, 103);		elm_grid_pack(vc->grid1, vc->label9, 177, 508, 262, 114);		elm_grid_pack(vc->grid1, vc->dkml, 435, 156, 397, 111);		elm_grid_pack(vc->grid1, vc->kml, 433, 264, 397, 111);		elm_grid_pack(vc->grid1, vc->akml, 431, 397, 397, 111);		elm_grid_pack(vc->grid1, vc->aml, 431, 506, 397, 111);		elm_grid_pack(vc->grid1, vc->dml, 431, 639, 397, 111);		elm_grid_pack(vc->grid1, vc->ml, 431, 750, 397, 111);		elm_grid_pack(vc->grid1, vc->hrml, 20, 506, 156, 111);		elm_grid_pack(vc->grid1, vc->label10, 20, 397, 156, 111);		elm_grid_pack(vc->grid1, vc->exitButton, 864, 372, 150, 250);		evas_object_show(vc->grid1);
	}
}

