/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "uib_views.h"
#include "uib_views_inc.h"

typedef struct _uib_view1_control_context {
 /* add your variables here */

} uib_view1_control_context;

void view1_exitButton_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	clean_exit();
}

void view1_topLabel_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	toggle_label_type();
}
