/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "gps.h"
#include "oauth_handler.h"
#include "uib_views.h"
#include "uib_views_inc.h"

typedef struct _uib_view1_control_context {
 /* add your variables here */

} uib_view1_control_context;

void view1_exitButton_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	clean_exit();
}

void view1_topLabel_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	gps_toggle_running();
}

void view1_bottomLabel_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	oauth_login();
}

void view1_label_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	gps_toggle_label();
}
